#include <string>

std::string JSON_ITEMS = "[\n"
"  {\n"
"    \"Category\": \"Rifle\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 101001,\n"
"        \"itemClass\": \"AKM\",\n"
"        \"itemName\": \"AKM\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101002,\n"
"        \"itemClass\": \"M16A4\",\n"
"        \"itemName\": \"M16A4\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101003,\n"
"        \"itemClass\": \"SCAR\",\n"
"        \"itemName\": \"SCAR-L\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101004,\n"
"        \"itemClass\": \"M416\",\n"
"        \"itemName\": \"M416\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101005,\n"
"        \"itemClass\": \"Groza\",\n"
"        \"itemName\": \"Groza\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101006,\n"
"        \"itemClass\": \"AUG\",\n"
"        \"itemName\": \"AUG A3\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101007,\n"
"        \"itemClass\": \"QBZ\",\n"
"        \"itemName\": \"QBZ\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101008,\n"
"        \"itemClass\": \"M762\",\n"
"        \"itemName\": \"M762\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101009,\n"
"        \"itemClass\": \"Mk47\",\n"
"        \"itemName\": \"Mk47 Mutant\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101010,\n"
"        \"itemClass\": \"G36\",\n"
"        \"itemName\": \"G36C\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 101100,\n"
"        \"itemClass\": \"FAMAS\",\n"
"        \"itemName\": \"FAMAS\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 105001,\n"
"        \"itemClass\": \"M249\",\n"
"        \"itemName\": \"M249\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 105002,\n"
"        \"itemClass\": \"DP28\",\n"
"        \"itemName\": \"DP-28\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Sub-MachineGun\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 102001,\n"
"        \"itemClass\": \"Uzi\",\n"
"        \"itemName\": \"UZI\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 102002,\n"
"        \"itemClass\": \"UMP9\",\n"
"        \"itemName\": \"UMP45\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 102003,\n"
"        \"itemClass\": \"Vector\",\n"
"        \"itemName\": \"Vector\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 102004,\n"
"        \"itemClass\": \"TommyGun\",\n"
"        \"itemName\": \"Tompson SMG\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 102005,\n"
"        \"itemClass\": \"PP19\",\n"
"        \"itemName\": \"PP-19 Bizon\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 102007,\n"
"        \"itemClass\": \"MP5K\",\n"
"        \"itemName\": \"Skorpion\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Sniper\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 103001,\n"
"        \"itemClass\": \"Kar98k\",\n"
"        \"itemName\": \"Kar98K\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103002,\n"
"        \"itemClass\": \"M24\",\n"
"        \"itemName\": \"M24\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103003,\n"
"        \"itemClass\": \"AWM\",\n"
"        \"itemName\": \"AWM\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103004,\n"
"        \"itemClass\": \"SKS\",\n"
"        \"itemName\": \"SKS\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103005,\n"
"        \"itemClass\": \"VSS\",\n"
"        \"itemName\": \"VSS\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103006,\n"
"        \"itemClass\": \"Mini14\",\n"
"        \"itemName\": \"Mini14\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103007,\n"
"        \"itemClass\": \"Mk14\",\n"
"        \"itemName\": \"Mk14\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103008,\n"
"        \"itemClass\": \"Win94\",\n"
"        \"itemName\": \"Win94\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103009,\n"
"        \"itemClass\": \"SLR\",\n"
"        \"itemName\": \"SLR\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103010,\n"
"        \"itemClass\": \"QBU\",\n"
"        \"itemName\": \"QBU\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103011,\n"
"        \"itemClass\": \"Mosin\",\n"
"        \"itemName\": \"Mosin Nagant Sniper Rifle\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 103100,\n"
"        \"itemClass\": \"MK12\",\n"
"        \"itemName\": \"Mk12\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"ShotGun\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 104001,\n"
"        \"itemClass\": \"S686\",\n"
"        \"itemName\": \"S686\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 104002,\n"
"        \"itemClass\": \"S1897\",\n"
"        \"itemName\": \"S1897\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 104003,\n"
"        \"itemClass\": \"S12K\",\n"
"        \"itemName\": \"S12K\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 104004,\n"
"        \"itemClass\": \"DP12\",\n"
"        \"itemName\": \"DP12\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 104101,\n"
"        \"itemClass\": \"M1014\",\n"
"        \"itemName\": \"M1014 Shotgun\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106006,\n"
"        \"itemClass\": \"SawedOff\",\n"
"        \"itemName\": \"Sawed-off\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Pistol\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 106001,\n"
"        \"itemClass\": \"P92\",\n"
"        \"itemName\": \"P92\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106002,\n"
"        \"itemClass\": \"P1911\",\n"
"        \"itemName\": \"P1911\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106003,\n"
"        \"itemClass\": \"R1895\",\n"
"        \"itemName\": \"R1895\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106004,\n"
"        \"itemClass\": \"P18C\",\n"
"        \"itemName\": \"P18C\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106005,\n"
"        \"itemClass\": \"R45\",\n"
"        \"itemName\": \"R45\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106008,\n"
"        \"itemClass\": \"Vz61\",\n"
"        \"itemName\": \"Vz61\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 106010,\n"
"        \"itemClass\": \"DesertEagle\",\n"
"        \"itemName\": \"Desert Eagle\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Other\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 107001,\n"
"        \"itemClass\": \"CrossBow\",\n"
"        \"itemName\": \"Crossbow\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Melee\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 108001,\n"
"        \"itemClass\": \"Machete\",\n"
"        \"itemName\": \"Machete\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 108002,\n"
"        \"itemClass\": \"Crowbar\",\n"
"        \"itemName\": \"Crowbar\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 108003,\n"
"        \"itemClass\": \"Sickle\",\n"
"        \"itemName\": \"Sickle\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 108004,\n"
"        \"itemClass\": \"Pan\",\n"
"        \"itemName\": \"Pan\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Attachment\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 201001,\n"
"        \"itemClass\": \"Choke\",\n"
"        \"itemName\": \"Choke\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201002,\n"
"        \"itemClass\": \"Compensator_SMG\",\n"
"        \"itemName\": \"Compensator (SMG)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201003,\n"
"        \"itemClass\": \"Compensator_Sniper\",\n"
"        \"itemName\": \"Compensator (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201004,\n"
"        \"itemClass\": \"FlashHider_SMG\",\n"
"        \"itemName\": \"Flash Hider (SMG)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201005,\n"
"        \"itemClass\": \"FlashHider_Sniper\",\n"
"        \"itemName\": \"Flash Hider (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201006,\n"
"        \"itemClass\": \"Suppressor_SMG\",\n"
"        \"itemName\": \"Suppressor (SMG)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201007,\n"
"        \"itemClass\": \"Suppressor_Sniper\",\n"
"        \"itemName\": \"Suppressor (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201009,\n"
"        \"itemClass\": \"Compensator_AR\",\n"
"        \"itemName\": \"Compensator (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201010,\n"
"        \"itemClass\": \"FlashHider_AR\",\n"
"        \"itemName\": \"Flash Hider (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201011,\n"
"        \"itemClass\": \"Suppressor_AR\",\n"
"        \"itemName\": \"Suppressor (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 201012,\n"
"        \"itemClass\": \"Duckbill\",\n"
"        \"itemName\": \"Duckbill (Shotguns)\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202001,\n"
"        \"itemClass\": \"AngledGrip\",\n"
"        \"itemName\": \"Angled Foregrip\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202002,\n"
"        \"itemClass\": \"VerticalGrip\",\n"
"        \"itemName\": \"Vertical Foregrip\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202004,\n"
"        \"itemClass\": \"LightGrip\",\n"
"        \"itemName\": \"Light Grip\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202005,\n"
"        \"itemClass\": \"HalfGrip\",\n"
"        \"itemName\": \"Half Grip\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202006,\n"
"        \"itemClass\": \"ThumbGrip\",\n"
"        \"itemName\": \"Thumb Grip\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 202007,\n"
"        \"itemClass\": \"LaserSight\",\n"
"        \"itemName\": \"Laser Sight\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203001,\n"
"        \"itemClass\": \"RedDot\",\n"
"        \"itemName\": \"Red Dot Sight\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203002,\n"
"        \"itemClass\": \"Holo\",\n"
"        \"itemName\": \"Holographic Sight\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203003,\n"
"        \"itemClass\": \"2x\",\n"
"        \"itemName\": \"2x Scope\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203004,\n"
"        \"itemClass\": \"4x\",\n"
"        \"itemName\": \"4x Scope\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203005,\n"
"        \"itemClass\": \"8x\",\n"
"        \"itemName\": \"8x Scope\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203014,\n"
"        \"itemClass\": \"3x\",\n"
"        \"itemName\": \"3x Scope\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203015,\n"
"        \"itemClass\": \"6x\",\n"
"        \"itemName\": \"6x Scope\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 203018,\n"
"        \"itemClass\": \"CantedSight\",\n"
"        \"itemName\": \"Canted Sight\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204014,\n"
"        \"itemClass\": \"BulletLoop\",\n"
"        \"itemName\": \"Bullet Loop (Shotguns, Sniper Rifles)\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 205001,\n"
"        \"itemClass\": \"UziStock\",\n"
"        \"itemName\": \"Stock (Micro UZI)\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 205002,\n"
"        \"itemClass\": \"TacticalStock\",\n"
"        \"itemName\": \"Tactical Stock (Rifles, SMG)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 205003,\n"
"        \"itemClass\": \"CheekPad\",\n"
"        \"itemName\": \"Cheek Pad (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 205004,\n"
"        \"itemClass\": \"Quiver\",\n"
"        \"itemName\": \"Quiver (Crossbow)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Mag\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 204004,\n"
"        \"itemClass\": \"ExtendedMag_SMG\",\n"
"        \"itemName\": \"Extended Mag (SMG, Pistols)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204005,\n"
"        \"itemClass\": \"QuickdrawMag_SMG\",\n"
"        \"itemName\": \"Quickdraw Mag (SMG, Pistols)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204006,\n"
"        \"itemClass\": \"ExtQuickdrawMag_SMG\",\n"
"        \"itemName\": \"Extended Quickdraw Mag (SMG, Pistols)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204007,\n"
"        \"itemClass\": \"ExtendedMag_Sniper\",\n"
"        \"itemName\": \"Extended Mag (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204008,\n"
"        \"itemClass\": \"QuickdrawMag_Sniper\",\n"
"        \"itemName\": \"Quickdraw Mag (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204009,\n"
"        \"itemClass\": \"ExtQuickdrawMag_Sniper\",\n"
"        \"itemName\": \"Extended Quickdraw Mag (Snipers)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204011,\n"
"        \"itemClass\": \"ExtendedMag_AR\",\n"
"        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204012,\n"
"        \"itemClass\": \"QuickdrawMag_AR\",\n"
"        \"itemName\": \"Quickdraw Mag (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 204013,\n"
"        \"itemClass\": \"ExtQuickdrawMag_AR\",\n"
"        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
"        \"itemTextColor\": \"0xFF9FBD1C\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Ammo\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 301001,\n"
"        \"itemClass\": \"9mm\",\n"
"        \"itemName\": \"9mm\",\n"
"        \"itemTextColor\": \"0xFF919AFF\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 302001,\n"
"        \"itemClass\": \"762mm\",\n"
"        \"itemName\": \"7.62mm\",\n"
"        \"itemTextColor\": \"0xFFFCC89D\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 303001,\n"
"        \"itemClass\": \"556mm\",\n"
"        \"itemName\": \"5.56mm\",\n"
"        \"itemTextColor\": \"0xFFD1EEEE\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 304001,\n"
"        \"itemClass\": \"12Gauge\",\n"
"        \"itemName\": \"12 Gauge\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 305001,\n"
"        \"itemClass\": \"45ACP\",\n"
"        \"itemName\": \".45 ACP\",\n"
"        \"itemTextColor\": \"0xFFF8FAB9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 306001,\n"
"        \"itemClass\": \"300Magnum\",\n"
"        \"itemName\": \".300 Magnum\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 307001,\n"
"        \"itemClass\": \"Bolt\",\n"
"        \"itemName\": \"Bolt\",\n"
"        \"itemTextColor\": \"0xFFFF66C9\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Bag\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 501001,\n"
"        \"itemClass\": \"Bag_Lv1\",\n"
"        \"itemName\": \"Backpack (Lv. 1)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 501002,\n"
"        \"itemClass\": \"Bag_Lv2\",\n"
"        \"itemName\": \"Backpack (Lv. 2)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 501006,\n"
"        \"itemClass\": \"Bag_Lv3\",\n"
"        \"itemName\": \"Backpack (Lv. 3)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Helmet\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 502001,\n"
"        \"itemClass\": \"Helmet_Lv1\",\n"
"        \"itemName\": \"Motorcycle Helmet (Lv. 1)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 502002,\n"
"        \"itemClass\": \"Helmet_Lv2\",\n"
"        \"itemName\": \"Military Helmet (Lv. 2)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 502003,\n"
"        \"itemClass\": \"Helmet_Lv3\",\n"
"        \"itemName\": \"Spetsnaz Helmet (Lv. 3)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Armor\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 503001,\n"
"        \"itemClass\": \"Armor_Lv1\",\n"
"        \"itemName\": \"Police Vest (Lv. 1)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 503002,\n"
"        \"itemClass\": \"Armor_Lv2\",\n"
"        \"itemName\": \"Police Vest (Lv. 2)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 503003,\n"
"        \"itemClass\": \"Armor_Lv3\",\n"
"        \"itemName\": \"Military Vest (Lv. 3)\",\n"
"        \"itemTextColor\": \"0xFFFFF266\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  {\n"
"    \"Category\": \"Medic\",\n"
"    \"Items\": [\n"
"      {\n"
"        \"itemId\": 601001,\n"
"        \"itemClass\": \"Drink\",\n"
"        \"itemName\": \"Energy Drink\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 601002,\n"
"        \"itemClass\": \"Injection\",\n"
"        \"itemName\": \"Adrenaline Syringe\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 601003,\n"
"        \"itemClass\": \"Pills\",\n"
"        \"itemName\": \"Painkiller\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 601004,\n"
"        \"itemClass\": \"Bandage\",\n"
"        \"itemName\": \"Bandage\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 601005,\n"
"        \"itemClass\": \"Firstaid\",\n"
"        \"itemName\": \"First Aid Kit\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      },\n"
"      {\n"
"        \"itemId\": 601006,\n"
"        \"itemClass\": \"FirstAidbox\",\n"
"        \"itemName\": \"Med Kit\",\n"
"        \"itemTextColor\": \"0xFF4DFF76\",\n"
"        \"itemOutlineColor\": \"0xFF000000\"\n"
"      }\n"
"    ]\n"
"  }\n"
"]";
